# Generated by Django 2.2 on 2020-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mark', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('complexity', models.IntegerField()),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
