# Generated by Django 2.2 on 2020-05-12 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
