# Generated by Django 2.2 on 2020-05-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0002_create_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
