# Generated by Django 2.2 on 2020-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0003_create_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_question',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='create_question',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='create_question',
            name='question_mark',
        ),
        migrations.AddField(
            model_name='create_question',
            name='ques_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
