# Generated by Django 2.2 on 2020-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0004_auto_20200521_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
