# Generated by Django 2.2 on 2020-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0006_create_question_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_question_history',
            name='created_at',
            field=models.DateField(),
        ),
    ]
