# Generated by Django 2.2 on 2020-05-21 17:30

import datetimeutc.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0008_auto_20200521_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question_history',
            name='submitted',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
