# Generated by Django 2.2 on 2020-05-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0009_create_question_history_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='create_question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='create_question_history',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='create_question_history',
            name='updated_at',
        ),
    ]
