# Generated by Django 2.2 on 2020-05-22 08:08

import datetimeutc.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0010_auto_20200522_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_question_history',
            old_name='submitted',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='create_question_history',
            name='updated_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
