# Generated by Django 2.2 on 2020-05-22 08:09

import datetimeutc.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0011_auto_20200522_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question',
            name='created_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_question',
            name='updated_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
