# Generated by Django 2.2 on 2020-05-22 08:12

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0012_auto_20200522_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_question_history',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='testapp6.create_question'),
        ),
        migrations.AlterField(
            model_name='create_question',
            name='updated_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='create_question_history',
            name='updated_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
    ]
