# Generated by Django 2.2 on 2020-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0014_auto_20200522_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_question',
            name='current_version_id',
        ),
        migrations.RemoveField(
            model_name='create_question_history',
            name='version_id',
        ),
    ]
