# Generated by Django 2.2 on 2020-05-29 06:30

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp6', '0015_auto_20200522_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_question_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(max_length=100)),
                ('importance', models.IntegerField(default=0)),
                ('created_at', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated_at', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
