# Generated by Django 2.1.4 on 2020-04-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='create_super_book',
            name='subject_name',
            field=models.ForeignKey(blank=True, default=0, on_delete='DO_NOTHING', related_name='subject_list', to='testapp2.add_subject'),
            preserve_default=False,
        ),
    ]
