# Generated by Django 2.1.4 on 2020-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0002_auto_20200406_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('button_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PanelButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_order', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete='DO_NOTHING', to='testapp2.Button')),
                ('panel', models.ForeignKey(on_delete='DO_NOTHING', to='testapp2.Panel')),
            ],
            options={
                'ordering': ('button_order',),
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='buttons',
            field=models.ManyToManyField(through='testapp2.PanelButtons', to='testapp2.Button'),
        ),
    ]
