# Generated by Django 2.1.4 on 2020-04-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill_book_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_book_name', models.CharField(max_length=155)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'skill_book_name',
            },
        ),
        migrations.CreateModel(
            name='skill_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category_name', models.CharField(max_length=155)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'skill_category',
            },
        ),
        migrations.AddField(
            model_name='skill_book_name',
            name='skill_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='testapp5.skill_category'),
        ),
    ]
