# Generated by Django 2.1.4 on 2020-04-16 07:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_topic_name', models.CharField(max_length=155)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'skill_topic',
            },
        ),
        migrations.AddField(
            model_name='skill_book_name',
            name='skill_topics_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill_topic',
            name='skill_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_book_names', to='testapp5.skill_book_name'),
        ),
    ]
