# Generated by Django 2.1.4 on 2020-04-11 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_slug', models.CharField(max_length=100, unique=True)),
                ('content_title', models.CharField(max_length=100)),
                ('content_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content_headline', models.CharField(max_length=100)),
                ('content_modifieddate', models.DateField()),
                ('content_createddate', models.DateField()),
            ],
        ),
    ]
