# Generated by Django 2.1.4 on 2020-04-12 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp3.Content')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_source_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('video_embed', models.TextField(blank=True, null=True)),
                ('video_copyright', models.TextField(blank=True, null=True)),
            ],
            bases=('testapp3.content',),
        ),
    ]
