# Generated by Django 2.2 on 2020-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginactivity',
            name='user_agent_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
